### ISSUE TITLE
Create release with last 3.0 branch commit

### ISSUE THREAD

**Issue by Zazama** [fractaslabs/silverstripe-cookie-policy-notification#11]
Hey,

could you create a 1.0.2 release for SilverStripe 3 including this commit https://github.com/fractaslabs/silverstripe-cookie-policy-notification/commit/1983111e12958e9e5a415d27e5d0c097d0c39fb6, because otherwise the 1.0.1 package is broken due to wrong js path.

**Comment by jelicanin** [comment]
Thanx @Zazama 
Issue fixed, pls check :)

**Comment by Zazama** [comment]
Cool, thank you so much!

**Comment by jelicanin** [comment]
👍
