### ISSUE TITLE
updates on packagist

### ISSUE THREAD

**Issue by spekulatius** [fractaslabs/silverstripe-cookie-policy-notification#8]
Hello,

I've noticed that the package on packagist isn't updated (name is outdated) and the release isn't listed:

https://packagist.org/packages/jelicanin/silverstripe-cookie-policy-notification

Maybe you want to add the hook on github so it updates automatically?

Cheers,
Peter

**Comment by hdpero** [comment]
Hi @spekulatius thank you for noticing. Hook has been added.
